
export type Language = 'en' | 'de';

export interface Project {
  id: string;
  title: string;
  category: { en: string; de: string };
  imageUrl: string;
  location: { en: string; de: string };
  year: string;
}

export interface Service {
  id: string;
  title: { en: string; de: string };
  description: { en: string; de: string };
  icon: string;
}

export interface Testimonial {
  id: string;
  quote: { en: string; de: string };
  author: string;
  role: { en: string; de: string };
  company: string;
}

export interface TeamMember {
  id: string;
  name: string;
  role: { en: string; de: string };
  imageUrl: string;
}

export interface Award {
  id: string;
  name: string;
  year: string;
  category: { en: string; de: string };
}

/**
 * Interface for the creative brief generated by the Gemini AI service.
 * Used for project conceptualization in the AIConsultant component.
 */
export interface CreativeBrief {
  conceptName: string;
  vibe: string;
  locations: string[];
  visualStyle: string;
  technicalRequirements: string[];
}
